#!/usr/bin/env bash

set -e
export -n CDPATH

if [ "$1" = "--debug" ]; then
  export UC_DEBUG=1
  shift
fi

if [ -n "$UC_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "uc: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${UC_ROOT}" ]; then
  UC_ROOT="${HOME}/.ubuntu-server-cli"
else
  UC_ROOT="${UC_ROOT%/}"
fi
export UC_ROOT

if [ -z "${UBUNTU_SERVER_CLI_DIR}" ]; then
  UBUNTU_SERVER_CLI_DIR="$(pwd)"
else
  cd "$UBUNTU_SERVER_CLI_DIR" 2>/dev/null || {
    echo "uc: cannot change working directory to \`$UBUNTU_SERVER_CLI_DIR'"
    exit 1
  } >&2
  UBUNTU_SERVER_CLI_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export UBUNTU_SERVER_CLI_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
export PATH="${bin_path}:${PATH}"

shopt -u nullglob

command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(uc-help)" >&2
  ;;
* )
  command_path="$(command -v "uc-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "Can not found command: \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
