#!/usr/bin/env bash
# Summary: Configure the shell environment for uc
# Usage: eval "$(uc init - [--no-rehash] [<shell>])"

set -e
[ -n "$UC_DEBUG" ] && set -x

print=""
no_rehash=""
for args in "$@"
do
  if [ "$args" = "-" ]; then
    print=1
    shift
  fi

  if [ "$args" = "--no-rehash" ]; then
    no_rehash=1
    shift
  fi
done

shell="$1"
if [ -z "$shell" ]; then
  shell="$(ps c -p $(ps -p $$ -o 'ppid=' 2>/dev/null) -o 'comm=' 2>/dev/null || true)"
  shell="${shell##-}"
  shell="$(basename "${shell:-$SHELL}")"
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "Can not found command: readlink!" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

root="$(abs_dirname "$0")/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    profile='~/.bash_profile'
    ;;
  zsh )
    profile='~/.zshrc'
    ;;
  ksh )
    profile='~/.profile'
    ;;
  fish )
    profile='~/.config/fish/config.fish'
    ;;
  * )
    profile='~/.profile'
    ;;
  esac

  { echo "# Load uc automatically by adding"
    echo "# the following to ${profile}:"
    echo
    case "$shell" in
    fish )
      echo '. (uc init -|psub)'
      ;;
    * )
      echo 'eval "$(uc init -)"'
      ;;
    esac
    echo
  } >&2

  exit 1
fi

case "$shell" in
fish )
  echo ". '$HOME/.ubuntu-server-cli/profile'"
;;
* )
  echo "source '$HOME/.ubuntu-server-cli/profile'"
;;
esac

completion="${root}/completions/uc.${shell}"
if [ -r "$completion" ]; then
  case "$shell" in
  fish ) echo ". '$completion'" ;;
  *    ) echo "source '$completion'" ;;
  esac
fi

if [ -z "$no_rehash" ]; then
  echo 'uc rehash 2>/dev/null'
fi

commands=(`uc-commands --sh`)
case "$shell" in
fish )
  cat <<EOS
function uc
  set command \$argv[1]
  set -e argv[1]

  switch "\$command"
  case ${commands[*]}
    eval (uc "sh-\$command" \$argv)
  case '*'
    command uc "\$command" \$argv
  end
end
EOS
  exit 0
  ;;
ksh )
  cat <<EOS
function uc {
  typeset command
EOS
  ;;
* )
  cat <<EOS
uc() {
  local command
EOS
  ;;
esac

IFS="|"
cat <<EOS
  command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  *)
    command uc "\$command" "\$@";;
  esac
}
EOS
